### ISSUE TITLE
error in ./create-omnidb-instance.sh

### ISSUE THREAD

**Issue by JavierMoralesEstevez** [OmniLayer/omni-devops#8] opened 2018-02-24 22:01 UTC
error when executing:
./create-omnidb-instance.sh
in ubuntu 16.04

> ./create-omnidb-instance.sh: 3: ./create-omnidb-instance.sh: rds-create-db-instance: not found

thanks you.

**Comment by msgilligan** [comment] 2018-02-25 21:07
Closing as an effective duplicate of Issue #10.

**Closed by msgilligan** 2018-02-25 21:07 UTC
