### ISSUE TITLE
error ssh: file must exist when I do  Vagrant up mastercore --provider=aws

### ISSUE THREAD

**Issue by JavierMoralesEstevez** [OmniLayer/omni-devops#7] opened 2018-02-23 21:32 UTC
error `private_key_path` file must exist:
when operating the following command line:
vagrant up mastercore --provider=aws

> `private_key_path` file must exist: 

I have installed aws tools and rds tools, I have also created my .pem file in amazon and download it. But I do not know where I should put it, I wrote in LocalVagrantConfig.rb the path (/home/user/key.pem) but the console indicates that file does not exist.

Any suggestions? Something must be wrong.
Thank you

**Comment by JavierMoralesEstevez** [comment] 2018-02-23 22:41
I have written the EXPORT of setup-omni-private and now I get the following error:

.........
> Bringing machine 'mastercore' up with 'aws' provider...
==> mastercore: Warning! The AWS provider doesn't support any of the Vagrant
==> mastercore: high-level network configurations (`config.vm.network`). They
==> mastercore: will be silently ignored.
==> mastercore: Launching an instance with the following settings...
==> mastercore:  -- Type: t2.small
==> mastercore:  -- AMI: ami-39501209
==> mastercore:  -- Region: us-east-1
==> mastercore:  -- Keypair: catalonia
==> mastercore:  -- Security Groups: ["sg-4b6a663c"]
==> mastercore:  -- Block Device Mapping: [{"DeviceName"=>"/dev/sda1", "Ebs.VolumeSize"=>60, "Ebs.DeleteOnTermination"=>false}]
==> mastercore:  -- Terminate On Shutdown: false
==> mastercore:  -- Monitoring: false
==> mastercore:  -- EBS optimized: false
==> mastercore:  -- Source Destination check: 
==> mastercore:  -- Assigning a public IP address in a VPC: false
==> mastercore:  -- VPC tenancy specification: default
==> mastercore: Warning! Vagrant might not be able to SSH into the instance.
==> mastercore: Please check your security groups settings.
There was an error talking to AWS. The error message is shown
below:

InvalidParameterValue => Value () for parameter groupId is invalid. The value cannot be empty

..................


Thanks you.

**Comment by JavierMoralesEstevez** [comment] 2018-02-25 20:26
Vagrant does not connect through ssh to the mastercore.
I have tried everything, but it is not possible for me. I do not understand why.

**Comment by msgilligan** [comment] 2018-02-25 21:08
I'm closing this as an effective duplicate of Issue #10.

**Closed by msgilligan** 2018-02-25 21:08 UTC
